# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HRlyLKQrpnKiaUE8tZcMTaif9U3erI86
"""

import requests
import json
import pandas as pd

api_key = 'c44ae648671f2e4bce10a02c0aa27618'
query = input("enter your need name:")
url = f'https://api.themoviedb.org/3/search/movie?query={query}&api_key={api_key}'
response = requests.get(url)
if response.status_code == 200:
  data = response.json()
  formatted_data = json.dumps(data, indent=4, sort_keys=True)

else:
  print("error",response.status_code)


df=pd.DataFrame(data['results'])
print(df[['title','release_date','vote_average']].to_string(index=False))

"""print(formatted_data) 先抓出json
看json的檔案再用pd
df=pd.DataFrame(data['results'])
print(df[['title','release_date','vote_average']])
print(data.keys())
"""